version: '3'

services:
  database:
    # Official Postgres image from DockerHub
    image: 'postgres:latest'
    # We use a volume to store the data of the database
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    # We expose the port 5432 to the outside world
    ports:
      - 5432:5432
    # POSTGRES_PASSWORD, POSTGRES_USER and POSTGRES_DB are environment variables used by the official Postgres image
    env_file:
      - .env
  test_database:
    image: 'postgres:latest'
    volumes:
      - ./test-db-data/:/var/lib/postgresql/data/
    # We expose the port 5433 to the outside world
    ports:
      - "5433:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_TEST_DB}

