version: '3'

services:
  database:
    # Official Postgres image from DockerHub (we use the last version)
    image: 'postgres:latest'
    # We use a volume to store the data of the database
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    # We expose the port 5432 to the outside world
    ports:
      - 5432:5432
    # POSTGRES_PASSWORD, POSTGRES_USER and POSTGRES_DB are environment variables used by the official Postgres image
    env_file:
      - .env 
